version: '3'
services:

  # Accounts microservice
  accounts:
    build:
      context: ./
      dockerfile: ./apps/accounts/Dockerfile
    env_file:
      - ./apps/accounts/.env
    depends_on:
      - rabbitmq
      - postgres_accounts
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Blacklist microservice
  blacklist:
    build:
      context: ./
      dockerfile: ./apps/blacklist/Dockerfile
    env_file:
      - ./apps/blacklist/.env
    depends_on:
      - rabbitmq
      - postgres_blacklist
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Orchestrator microservice
  orchestrator:
    build:
      context: ./
      dockerfile: ./apps/orchestrator/Dockerfile
    env_file:
      - ./apps/orchestrator/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  # Transactions microservice
  transactions:
    build:
      context: ./
      dockerfile: ./apps/transactions/Dockerfile
    env_file:
      - ./apps/transactions/.env
    depends_on:
      - rabbitmq
      - postgres_transactions
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  # Postgres accounts
  postgres_accounts:
    image: postgres
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: transactions_user
      POSTGRES_PASSWORD: transactions_password
    volumes:
      - postgres_accounts:/var/lib/postgresql/data

  # Postgres blacklist
  postgres_blacklist:
    image: postgres
    ports:
      - 5434:5434
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: transactions_user
      POSTGRES_PASSWORD: transactions_password
    volumes:
      - postgres_blacklist:/var/lib/postgresql/data

  # Postgres transactions
  postgres_transactions:
    image: postgres
    ports:
      - 5435:5435
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: transactions_user
      POSTGRES_PASSWORD: transactions_password
    volumes:
      - postgres_transactions:/var/lib/postgresql/data
  
  # Message broker (RabbitMQ)
  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - 5672:5672
      - "15672:15672"

volumes:
  postgres_accounts:
  postgres_blacklist:
  postgres_transactions:
